/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const gltf = useGLTF("/scene.glb");
  const { nodes, materials } = gltf;
  console.log(gltf);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-1.51, 1.12, -1.13]}>
        <pointLight
          intensity={50}
          decay={2}
          color="#ff11f2"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[1.77, 1.57, 1.3]}>
        <pointLight
          intensity={40}
          decay={2}
          color="#0c0cff"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <group position={[-2.09, -1.35, 1.93]}>
        <pointLight
          intensity={20}
          decay={2}
          color="#fff21c"
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        material={materials.Wall}
        geometry={nodes.Cube.geometry}
        scale={[2.71, 2.71, 2.71]}
      />
      <mesh
        material={materials.Ball}
        geometry={nodes.Sphere.geometry}
        position={[-1.61, -1.63, -1.63]}
      />
      <mesh
        material={materials.Cube}
        geometry={nodes.Cube001.geometry}
        position={[0.95, -0.89, 0.74]}
        rotation={[0.26, 0.14, 0.48]}
      />
    </group>
  );
}

useGLTF.preload("/scene.glb");
